[[servers]]
host = "ldap.domain.com"
#port = 636
port = 389
use_ssl = false
start_tls = false
ssl_skip_verify = false
bind_dn = "CN=service-account,OU=Service Accounts,OU=Atlanta,DC=domain,DC=com"
bind_password = "Pa$$word1!"
search_filter = "(sAMAccountName=%s)"
search_base_dns = ["dc=domain,dc=com"]

[servers.attributes]
name = "givenName"
username = "sAMAccountName"
member_of = "memberOf"
email =  "userPrincipalName"

[[servers.group_mappings]]
group_dn = "cn=ittools,ou=groups,ou=Atlanta,dc=domain,dc=com"
org_role = "Admin"                      # Grafana Admin role
grafana_admin = true

[[servers.group_mappings]]
group_dn = "cn=ocp_admin,ou=groups,ou=Atlanta,dc=domain,dc=com"
org_role = "Admin"                     # Grafana Viewer role

[[servers.group_mappings]]
group_dn = "cn=tfs_admin,ou=groups,ou=Atlanta,dc=domain,dc=com"
org_role = "Editor"                     # Grafana Editor role

[[servers.group_mappings]]
group_dn = "cn=Infra_VMWare,ou=groups,ou=Atlanta,dc=domain,dc=com"
org_role = "Editor"                     # Grafana Editor Role

[[servers.group_mappings]]
group_dn = "cn=all_people,ou=powerbipro,ou=azuregroups,ou=groups,ou=Atlanta,dc=domain,dc=com"
org_role = "Viewer"                     # Grafana Viewer role